openapi: 3.0.0
info:
  title: API Quản lý sách của Hưng
  description: Hệ thống quản lý thư viện đơn giản chức năng cơ bản.
  version: 1.0.0
paths:
  /books:
    get:
      summary: Lấy danh sách tất cả các sách
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Thêm một cuốn sách mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Tạo sách thành công

  /books/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID của cuốn sách
        schema:
          type: integer
    get:
      summary: Lấy chi tiết một cuốn sách
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Không tìm thấy sách
    put:
      summary: Cập nhật thông tin sách
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Không tìm thấy sách để cập nhật
    delete:
      summary: Xóa một cuốn sách
      responses:
        '204':
          description: Xóa thành công
        '404':
          description: Không tìm thấy sách để xóa

components:
  schemas:
    Book:
      type: object
      required:
        - title
        - author
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Dế Mèn Phiêu Lưu Ký"
        author:
          type: string
          example: "Tô Hoài"