#%RAML 1.0
title: API Quan ly sach
version: 1.0.0
baseUri: http://api.thuvien.local

types:
  Book:
    type: object
    properties:
      id?: integer
      title: string
      author: string

/books:
  get:
    description: Lay tat ca cac sach
    responses:
      200:
        body:
          application/json:
            type: Book[]
            example: |
              [
                {
                  "id": 1,
                  "title": "De Men phieu luu ky",
                  "author": "To Hoai"
                }
              ]
  post:
    description: Them mot cuon sach moi
    body:
      application/json:
        properties:
          title: string
          author: string
        example: |
          {
            "title": "So Do",
            "author": "Vu Trong Phung"
          }
    responses:
      201:
        body:
          application/json:
            type: Book
            example: |
              {
                "id": 2,
                "title": "So Do",
                "author": "Vu Trong Phung"
              }